{
 "title": "CAdvisor",
 "tags": [
  "cadvisor",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({job=\"data-superset-cadvisor\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])\n/\non() group_left()\ncount(node_cpu_seconds_total{job=~\"data-superset-node-exporter\", instance=~\"data:superset:srv-03-data:superset\", mode=\"idle\"}) \n* 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{job=\"data-superset-cadvisor\", name=~\"$container\"}\n  /\n  on() group_left()\n  node_memory_MemTotal_bytes{job=~\"data-superset-node-exporter\", instance=~\"data:superset:srv-03-data:superset\"} * 100\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(container_memory_working_set_bytes{job=\"data-superset-cadvisor\"}) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])\n/\non() group_left()\ncount(node_cpu_seconds_total{job=~\"data-superset-node-exporter\", instance=~\"data:superset:srv-03-data:superset\", mode=\"idle\"}) \n* 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{job=\"data-superset-cadvisor\", name=~\"$container\"}\n  /\n  on() group_left()\n  node_memory_MemTotal_bytes{job=~\"data-superset-node-exporter\", instance=~\"data:superset:srv-03-data:superset\"} * 100\n) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container/VM CPU Limit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_spec_cpu_quota{job=\"data-superset-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"} / 100000) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"data-superset-node-exporter\", instance=~\"data:superset:srv-03-data:superset\", mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container/VM Memory Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{job=\"data-superset-cadvisor\", name=~\"$container\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"data-superset-node-exporter\", instance=~\"data:superset:srv-03-data:superset\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container BLKIO Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"data-superset-cadvisor\", name=~\"$container\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Device BLKIO Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Network Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])) by (interface)",
     "legendFormat": "receive - {{interface}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])) by (interface)",
     "legendFormat": "transmit - {{interface}}"
    }
   ]
  },
  {
   "title": "Workload Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{job=\"data-superset-cadvisor\", name=~\"$container\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(\n  container_memory_working_set_bytes{job=\"data-superset-cadvisor\", name=~\"$container\"}\n  /\n  on() group_left()\n  node_memory_MemTotal_bytes{job=~\"data-superset-node-exporter\", instance=~\"data:superset:srv-03-data:superset\"} * 100\n) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{job=\"data-superset-cadvisor\", name=~\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container Memory Limit",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{job=\"data-superset-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container) > 0\n",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization by Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "$A / $B", "type": "math" }
     ]
    },
    {
     "title": "Total CPU Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 3 },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU Limit by Container",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_spec_cpu_quota{job=\"data-superset-cadvisor\", name=~\"$container\"} / 100000) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "User CPU Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_user_seconds_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "System CPU Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 12 },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_system_seconds_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU Throttling Rate by Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((rate(container_cpu_cfs_throttled_periods_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[1m]) / rate(container_cpu_cfs_periods_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[1m])) * 100) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average CPU Throttled Time per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[1m]) / rate(container_cpu_cfs_throttled_periods_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total BLKIO Usage Per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read vs. Write BLKIO Usage Per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-superset-cadvisor\", name=~\"$container\", operation=\"Read\"}[5m])) by (name)",
       "legendFormat": "read - {{name}}"
      },
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-superset-cadvisor\", name=~\"$container\", operation=\"Write\"}[5m])) by (name)",
       "legendFormat": "write - {{name}}"
      }
     ]
    },
    {
     "title": "Total BLKIO Usage Per Device",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])) by (device)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Transmitted Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{job=\"data-superset-cadvisor\", name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}