{
 "title": "Nodes",
 "description": "Used Jobs:\n- \"kraft-node-exporter\"",
 "tags": [
  "node-exporter",
  "kraft"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"kraft-node-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"idle\"}[5m])) * 100))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - ((node_memory_MemAvailable_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}) / (node_memory_MemTotal_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_filesystem_avail_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"}))",
     "legendFormat": "OS"
    },
    {
     "expr": "avg(100 - ((node_filesystem_avail_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\", fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\", fstype!=\"rootfs\"}))",
     "legendFormat": "Kraft"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Load Average 1 minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Total / Available",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"kraft-node-exporter\", instance=~\"$instance\"} - node_boot_time_seconds{job=\"kraft-node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"idle\"}[5m])) * 100 )",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Utilization by Mode",
     "type": "timeseries",
     "description": "System - Processes executing in kernel mode\nUser - Normal processes executing in user mode\nNice - Niced processes executing in user mode\nIOWait - Waiting for I/O to complete\nIRQ - Servicing interrupts\nSoftIRQ - Servicing softirqs\nSteal - Time spent in other operating systems when running in a virtualized environment\nIdle - Waiting for something to happen",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"system\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"user\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "User"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"nice\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "Nice"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=~\"iowait\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "IOWait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=~\"irq\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "IRQ"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"softirq\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "SoftIRQ"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"steal\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "Steal"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"idle\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU Utilization",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\", mode=\"idle\"}[5m])) * 100))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "System Load Average 1 minute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{job=\"kraft-node-exporter\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Interrupts by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_intr_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "System Load Average 1 minute",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load1{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Context Switches by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_context_switches_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Context Switch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(irate(node_context_switches_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Interrupt",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(irate(node_intr_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - ((node_memory_MemAvailable_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}) / (node_memory_MemTotal_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RAM Total / Available",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(node_memory_MemAvailable_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Average Memory Utilization",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((1 - ((node_memory_MemAvailable_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}) / (node_memory_MemTotal_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Memory Stack",
     "type": "timeseries",
     "description": "Apps - Memory used by user-space applications\n\nPageTables - Memory used to map between virtual and physical memory addresses\n\nSwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified\n\nSlab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)\n\nCache - Parked file data (file content) cache\n\nBuffers - Block device (e.g. harddisk) cache\n\nUnused - Free memory unassigned\n\nSwap - Swap space used\n\nHardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} - node_memory_MemFree_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} - node_memory_Buffers_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} - node_memory_Cached_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} - node_memory_Slab_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} - node_memory_PageTables_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} - node_memory_SwapCached_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Apps"
      },
      {
       "expr": "avg((node_memory_PageTables_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "PageTables"
      },
      {
       "expr": "avg(node_memory_SwapCached_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "SwapCache"
      },
      {
       "expr": "avg((node_memory_Slab_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Slab"
      },
      {
       "expr": "avg((node_memory_Cached_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Cache"
      },
      {
       "expr": "avg((node_memory_Buffers_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Buffers"
      },
      {
       "expr": "avg((node_memory_MemFree_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Unused"
      },
      {
       "expr": "avg((node_memory_SwapTotal_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} - node_memory_SwapFree_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Swap"
      },
      {
       "expr": "avg((node_memory_HardwareCorrupted_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Hardware Corrupted"
      }
     ]
    },
    {
     "title": "Average Memory Active / Inactive Detail",
     "type": "timeseries",
     "description": "Inactive_file - File-backed memory on inactive LRU list\n\nInactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)\n\nActive_file - File-backed memory on active LRU list\n\nActive_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(node_memory_Inactive_file_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Inactive_file"
      },
      {
       "expr": "avg(node_memory_Inactive_anon_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Inactive_anon"
      },
      {
       "expr": "avg(node_memory_Active_file_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Active_file"
      },
      {
       "expr": "avg(node_memory_Active_anon_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Active_anon"
      }
     ]
    },
    {
     "title": "Average Memory Active / Inactive",
     "type": "stat",
     "description": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes\n\nActive - Memory that has been used more recently and usually not reclaimed unless absolutely necessary",
     "gridPos": { "h": 8, "w": 2, "x": 22, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_memory_Inactive_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Inactive"
      },
      {
       "expr": "avg(node_memory_Active_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Active"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "timeseries",
     "description": "Writeback - Memory which is actively being written back to disk\n\nWritebackTmp - Memory used by FUSE for temporary writeback buffers\n\nDirty - Memory which is waiting to get written back to the disk",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_Writeback_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Writeback"
      },
      {
       "expr": "sum(node_memory_WritebackTmp_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "WritebackTmp"
      },
      {
       "expr": "sum(node_memory_Dirty_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Dirty"
      }
     ]
    },
    {
     "title": "Average Memory Shared and Mapped",
     "type": "timeseries",
     "description": "Mapped - Used memory in mapped pages files which have been mapped, such as libraries\n\nShmem - Used shared memory (shared between several processes, thus including RAM disks)\n\nShmemHugePages - Memory used by shared memory (shmem) and tmpfs allocated  with huge pages\n\nShmemPmdMapped - Amount of shared (shmem/tmpfs) memory backed by huge pages",
     "gridPos": { "h": 5, "w": 11, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(node_memory_Mapped_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Mapped"
      },
      {
       "expr": "avg(node_memory_Shmem_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Shmem"
      },
      {
       "expr": "avg(node_memory_ShmemHugePages_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "ShmemHugePages"
      },
      {
       "expr": "avg(node_memory_ShmemPmdMapped_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "ShmemPmdMapped"
      }
     ]
    },
    {
     "title": "Average Memory Committed",
     "type": "stat",
     "description": "Committed_AS - Amount of memory presently allocated on the system\n\nCommitLimit - Amount of  memory currently available to be allocated on the system",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_memory_Committed_AS_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Committed_AS"
      },
      {
       "expr": "avg(node_memory_CommitLimit_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "CommitLimit"
      }
     ]
    },
    {
     "title": "Memory Anonymous",
     "type": "timeseries",
     "description": "AnonHugePages - Memory in anonymous huge pages\n\nAnonPages - Memory in user pages not backed by files",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(node_memory_AnonHugePages_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "AnonHugePages"
      },
      {
       "expr": "avg(node_memory_AnonPages_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "AnonPages"
      }
     ]
    },
    {
     "title": "Average Memory Kernel / CPU",
     "type": "timeseries",
     "description": "KernelStack - Kernel memory stack. This is not reclaimable\n\nPerCPU - Per CPU memory allocated dynamically by loadable modules",
     "gridPos": { "h": 5, "w": 11, "x": 11, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(node_memory_KernelStack_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "KernelStack"
      },
      {
       "expr": "avg(node_memory_Percpu_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "PerCPU"
      }
     ]
    },
    {
     "title": "Average Memory Pages In / Out",
     "type": "timeseries",
     "description": "Pagesin - Page in operations\n\nPagesout - Page out operations",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(node_vmstat_pgpgin{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Pagesin"
      },
      {
       "expr": "avg(irate(node_vmstat_pgpgout{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Pagesout"
      }
     ]
    },
    {
     "title": "Average Memory Page Faults",
     "type": "timeseries",
     "description": "Pgfault - Page major and minor fault operations\n\nPgmajfault - Major page fault operations\n\nPgminfault - Minor page fault operations",
     "gridPos": { "h": 5, "w": 11, "x": 11, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(node_vmstat_pgfault{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Pgfault"
      },
      {
       "expr": "avg(irate(node_vmstat_pgmajfault{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Pgmajfault"
      },
      {
       "expr": "avg(irate(node_vmstat_pgfault{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])  - irate(node_vmstat_pgmajfault{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Pgminfault"
      }
     ]
    },
    {
     "title": "Average Memory Slab",
     "type": "stat",
     "description": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure\n\nSReclaimable - Part of Slab, that might be reclaimed, such as caches",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_memory_SUnreclaim_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "SUnreclaim"
      },
      {
       "expr": "avg(node_memory_SReclaimable_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "SReclaimable"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "{{instance}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "{{instance}} - Transmit"
      }
     ]
    },
    {
     "title": "Bytes by Device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device!~\"lxc.*\"}[$__rate_interval]) * 8) by (device)",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device!~\"lxc.*\"}[$__rate_interval]) * 8) by (device)",
       "legendFormat": "{{device}} - Transmit"
      },
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device=~\"lxc.*\"}[$__rate_interval]) * 8) ",
       "legendFormat": "lxc* - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device=~\"lxc.*\"}[$__rate_interval]) * 8) ",
       "legendFormat": "lxc* - Transmit"
      }
     ]
    },
    {
     "title": "Total Bytes",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Packets by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_packets_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Transmit"
      }
     ]
    },
    {
     "title": "Packets by Device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_packets_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device!~\"lxc.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device!~\"lxc.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Transmit"
      },
      {
       "expr": "sum(irate(node_network_receive_packets_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device=~\"lxc.*\"}[$__rate_interval]))",
       "legendFormat": "lxc* - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device=~\"lxc.*\"}[$__rate_interval]))",
       "legendFormat": "lxc* - Transmit"
      }
     ]
    },
    {
     "title": "Total Packets",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_packets_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Packet Drop by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_drop_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Receive drop"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Packet Drop by Device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_drop_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device!~\"lxc.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device!~\"lxc.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Transmit drop"
      },
      {
       "expr": "sum(irate(node_network_receive_drop_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device=~\"lxc.*\"}[$__rate_interval]))",
       "legendFormat": "lxc* - Receive drop"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{job=\"kraft-node-exporter\", instance=~\"$instance\", device=~\"lxc.*\"}[$__rate_interval]))",
       "legendFormat": "lxc* - Transmit drop"
      }
     ]
    },
    {
     "title": "Total Packet Drop",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_drop_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Softnet Packets by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_softnet_processed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Processed"
      },
      {
       "expr": "sum(irate(node_softnet_dropped_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Dropped"
      }
     ]
    },
    {
     "title": "Softnet Packets by CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_softnet_processed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (cpu)",
       "legendFormat": "CPU {{cpu}} - Processed"
      },
      {
       "expr": "sum(irate(node_softnet_dropped_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (cpu)",
       "legendFormat": "CPU {{cpu}} - Dropped"
      }
     ]
    },
    {
     "title": "Total Softnet Packets",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_softnet_processed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Processed"
      },
      {
       "expr": "sum(irate(node_softnet_dropped_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Dropped"
      }
     ]
    },
    {
     "title": "Softnet Out of Quota by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_softnet_times_squeezed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Softnet Out of Quota by CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_softnet_times_squeezed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (cpu)",
       "legendFormat": "{{cpu}} - Squeezed"
      }
     ]
    },
    {
     "title": "Total Softnet Out of Quota",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_softnet_times_squeezed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockstat TCP by Instance",
     "type": "timeseries",
     "description": "TCP_alloc - Allocated sockets\n\nTCP_inuse - Tcp sockets currently in use\n\nTCP_mem - Used memory for tcp\n\nTCP_orphan - Orphan sockets\n\nTCP_tw - Sockets waiting close",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_sockstat_TCP_alloc{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance) + sum(node_sockstat_TCP_inuse{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance) + sum(node_sockstat_TCP_mem{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance) + sum(node_sockstat_TCP_orphan{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance) + sum(node_sockstat_TCP_tw{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Sockstat TCP by Type",
     "type": "timeseries",
     "description": "TCP_alloc - Allocated sockets\n\nTCP_inuse - Tcp sockets currently in use\n\nTCP_mem - Used memory for tcp\n\nTCP_orphan - Orphan sockets\n\nTCP_tw - Sockets waiting close",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_sockstat_TCP_alloc{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "sum(node_sockstat_TCP_inuse{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "TCP_inuse"
      },
      {
       "expr": "sum(node_sockstat_TCP_mem{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "TCP_mem"
      },
      {
       "expr": "sum(node_sockstat_TCP_orphan{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "TCP_orphan"
      },
      {
       "expr": "sum(node_sockstat_TCP_tw{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "TCP_tw"
      }
     ]
    },
    {
     "title": "Sockstat UDP by Instance",
     "type": "timeseries",
     "description": "UDPLITE_inuse - Udplite sockets currently in use\n\nUDP_inuse - Udp sockets currently in use\n\nUDP_mem - Used memory for udp",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_sockstat_UDPLITE_inuse{job=\"kraft-node-exporter\", instance=~\"$instance\"} + node_sockstat_UDP_inuse{job=\"kraft-node-exporter\", instance=~\"$instance\"} + node_sockstat_UDP_mem{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Sockstat UDP by Type",
     "type": "timeseries",
     "description": "UDPLITE_inuse - Udplite sockets currently in use\n\nUDP_inuse - Udp sockets currently in use\n\nUDP_mem - Used memory for udp",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_sockstat_UDPLITE_inuse{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "UDPLITE_inuse"
      },
      {
       "expr": "sum(node_sockstat_UDP_inuse{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "UDP_inuse"
      },
      {
       "expr": "sum(node_sockstat_UDP_mem{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "UDP_mem"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size by Instance",
     "type": "timeseries",
     "description": "mem_bytes - TCP sockets in that state\n\nmem_bytes - UDP sockets in that state\n\nFRAG_memory - Used memory for frag",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_sockstat_TCP_mem_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} + node_sockstat_UDP_mem_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"} + node_sockstat_FRAG_memory{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size by Type",
     "type": "timeseries",
     "description": "mem_bytes - TCP sockets in that state\n\nmem_bytes - UDP sockets in that state\n\nFRAG_memory - Used memory for frag",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_sockstat_TCP_mem_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "mem_bytes"
      },
      {
       "expr": "sum(node_sockstat_UDP_mem_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "mem_bytes"
      },
      {
       "expr": "sum(node_sockstat_FRAG_memory{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "FRAG_memory"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "timeseries",
     "description": "Sockets currently in use",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_sockstat_sockets_used{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat IP In / Out Octets by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_IpExt_InOctets{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) + irate(node_netstat_IpExt_OutOctets{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Netstat IP In / Out Octets by Type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_IpExt_InOctets{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "InOctets"
      },
      {
       "expr": "sum(irate(node_netstat_IpExt_OutOctets{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "OutOctets "
      }
     ]
    },
    {
     "title": "ICMP In / Out by Instance",
     "type": "timeseries",
     "description": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors\n\nOutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Icmp_InMsgs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) + irate(node_netstat_Icmp_OutMsgs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ICMP In / Out by Type",
     "type": "timeseries",
     "description": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors\n\nOutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Icmp_InMsgs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "InMsgs"
      },
      {
       "expr": "sum(irate(node_netstat_Icmp_OutMsgs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "OutMsgs"
      }
     ]
    },
    {
     "title": "TCP / UDP In / Out by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Udp_InDatagrams{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) + irate(node_netstat_Udp_OutDatagrams{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) + irate(node_netstat_Tcp_InSegs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) + irate(node_netstat_Tcp_OutSegs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "UDP / TCP In / Out by Type",
     "type": "timeseries",
     "description": "InUDP - Datagrams received\n\nOutUDP - Datagrams sent\n\nInTCP- Segments received, including those received in error. This count includes segments received on currently established connections\n\nOutTCP - Segments sent, including those on current connections but excluding those containing only retransmitted octets",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Udp_InDatagrams{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "InUDP"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_OutDatagrams{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "OutUDP"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_InSegs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "InTCP"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_OutSegs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "OutTCP"
      }
     ]
    },
    {
     "title": "TCP Errors by Instance",
     "type": "timeseries",
     "description": "ListenOverflows - Times the listen queue of a socket overflowed\n\nListenDrops - SYNs to LISTEN sockets ignored\n\nTCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits\n\nRetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_TcpExt_ListenOverflows{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance) + sum(irate(node_netstat_TcpExt_ListenDrops{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance) + sum(irate(node_netstat_TcpExt_TCPSynRetrans{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance) + sum(irate(node_netstat_Tcp_RetransSegs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance) + sum(irate(node_netstat_Tcp_InErrs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance) + sum(irate(node_netstat_Tcp_OutRsts{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance) + sum(irate(node_netstat_TcpExt_TCPOFOQueue{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TCP Errors by Type",
     "type": "timeseries",
     "description": "ListenOverflows - Times the listen queue of a socket overflowed\n\nListenDrops - SYNs to LISTEN sockets ignored\n\nTCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits\n\nRetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets\n\nInErrs - Segments received in error (e.g., bad TCP checksums)\n\nOutRsts - Segments sent with RST flag\n\nTCPOFOQueue - TCP layer receives an out of order packet and has enough memory to queue it",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_TcpExt_ListenOverflows{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ListenOverflows "
      },
      {
       "expr": "sum(irate(node_netstat_TcpExt_ListenDrops{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ListenDrops"
      },
      {
       "expr": "sum(irate(node_netstat_TcpExt_TCPSynRetrans{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "TCPSynRetrans"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_RetransSegs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "RetransSegs"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_InErrs{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "InErrs"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_OutRsts{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "OutRsts"
      },
      {
       "expr": "sum(irate(node_netstat_TcpExt_TCPOFOQueue{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "TCPOFOQueue"
      }
     ]
    },
    {
     "title": "TCP Direct Transition by Instance",
     "type": "timeseries",
     "description": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state\n\nPassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Tcp_ActiveOpens{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) + irate(node_netstat_Tcp_PassiveOpens{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TCP Direct Transition by Type",
     "type": "timeseries",
     "description": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state\n\nPassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Tcp_ActiveOpens{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ActiveOpens"
      },
      {
       "expr": "sum(irate(node_netstat_Tcp_PassiveOpens{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "PassiveOpens"
      }
     ]
    },
    {
     "title": "CurrEstab TCP Connections by Instance",
     "type": "timeseries",
     "description": "،CP connections for which the current state is either ESTABLISHED or CLOSE- WAIT",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_netstat_Tcp_CurrEstab{job=\"kraft-node-exporter\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total CurrEstab TCP Connections",
     "type": "stat",
     "description": "،CP connections for which the current state is either ESTABLISHED or CLOSE- WAIT",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_netstat_Tcp_CurrEstab{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "OS Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"} * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"})",
       "legendFormat": "Average Total"
      }
     ]
    },
    {
     "title": "OS Free Space",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kraft Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\"} - node_filesystem_avail_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\"}) / node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\"} * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kraft Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\"} - node_filesystem_avail_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(node_filesystem_size_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\"})",
       "legendFormat": "Average Total"
      }
     ]
    },
    {
     "title": "Kraft Free Space",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{job=\"kraft-node-exporter\", instance=~\"$instance\", mountpoint=\"/mnt/disk-2\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk IOps Completed by Instance",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_reads_completed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Reads completed"
      },
      {
       "expr": "avg(irate(node_disk_writes_completed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk IOps Completed by Device",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_reads_completed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "avg(irate(node_disk_writes_completed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Average Disk IOps Completed",
     "type": "stat",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_reads_completed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Reads completed"
      },
      {
       "expr": "avg(irate(node_disk_writes_completed_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Writes completed"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Time Synchronized Drift",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(node_timex_estimated_error_seconds{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "avg(node_timex_offset_seconds{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Time offset in between local system and reference clock"
      },
      {
       "expr": "avg(node_timex_maxerror_seconds{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    },
    {
     "title": "Average Processes Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(node_procs_blocked{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "avg(node_procs_running{job=\"kraft-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "Processes forks second by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_forks_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Process schedule stats Running / Waiting",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(irate(node_schedstat_running_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (cpu)",
       "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
      },
      {
       "expr": "avg(irate(node_schedstat_waiting_seconds_total{job=\"kraft-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (cpu)",
       "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
      }
     ]
    }
   ]
  }
 ]
}