{
 "title": "API Server",
 "description": "Used Jobs:\n- \"data-k8s-api-server\"",
 "tags": [
  "kubernetes",
  "api-server"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(apiserver_request_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "99th Percentile of Kubernetes API Server Request Latency by Verb",
     "type": "timeseries",
     "description": "A high value indicates that certain requests are taking longer than expected, which could signal issues like API server overload or inefficient request handling. A low value means the API server is responding efficiently.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"data-data-k8s-api-server\", instance=~\"$instance\", verb!=\"\"}[5m])) by (verb, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubernetes API Server Request Latency by Group",
     "type": "timeseries",
     "description": "A high value indicates that certain requests are taking longer than expected, which could signal issues like API server overload or inefficient request handling. A low value means the API server is responding efficiently.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"data-data-k8s-api-server\", instance=~\"$instance\", group!=\"\"}[5m])) by (group, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubernetes API Server Request Latency by Resource",
     "type": "timeseries",
     "description": "A high value indicates that certain requests are taking longer than expected, which could signal issues like API server overload or inefficient request handling. A low value means the API server is responding efficiently.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"data-data-k8s-api-server\", instance=~\"$instance\", resource!=\"\"}[5m])) by (le, resource))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubernetes API Server Request Latency by Scope",
     "type": "timeseries",
     "description": "A high value indicates that certain requests are taking longer than expected, which could signal issues like API server overload or inefficient request handling. A low value means the API server is responding efficiently.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"data-data-k8s-api-server\", instance=~\"$instance\", scope!=\"\"}[5m])) by (le,scope))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubernetes API Server Request Latency by Subprocess",
     "type": "timeseries",
     "description": "A high value indicates that certain requests are taking longer than expected, which could signal issues like API server overload or inefficient request handling. A low value means the API server is responding efficiently.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"data-data-k8s-api-server\", instance=~\"$instance\", subresource!=\"\"}[5m])) by (le, subresource))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubernetes API Server Request Latency by Version",
     "type": "timeseries",
     "description": "A high value indicates that certain requests are taking longer than expected, which could signal issues like API server overload or inefficient request handling. A low value means the API server is responding efficiently.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"data-data-k8s-api-server\", instance=~\"$instance\", version!=\"\"}[5m])) by (le, version))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Request Rate by Resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-k8s-api-server\", instance=~\"$instance\", resource!=\"\"}[5m])) by (resource)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Request Rate by Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-k8s-api-server\", instance=~\"$instance\", group!=\"\"}[5m])) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Request Rate by Subresource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-k8s-api-server\", instance=~\"$instance\", subresource!=\"\"}[5m])) by (subresource)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Request Rate by Scope",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-k8s-api-server\", instance=~\"$instance\", scope!=\"\"}[5m])) by (scope)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Request Rate by Verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-k8s-api-server\", instance=~\"$instance\", verb!=\"\"}[5m])) by (verb)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Request Rate by Response Code",
   "type": "stat",
   "description": "2xx: Successful requests. A high value indicates normal functioning, where most API calls are processed without issues.\n3xx: Redirected requests. A moderate or low value is normal, as redirection should be occasional. A high value could indicate inefficiencies.\n4xx: Client errors. A high value suggests issues like bad requests or authorization failures, indicating potential misconfigurations or permission problems.\n5xx: Server errors. A high value is a critical issue, showing server-side problems in processing requests, which may lead to service disruption.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-data-k8s-api-server\", instance=~\"$instance\", code=~\"2..\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-data-k8s-api-server\", instance=~\"$instance\", code=~\"3..\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-data-k8s-api-server\", instance=~\"$instance\", code=~\"4..\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-data-k8s-api-server\", instance=~\"$instance\", code=~\"5..\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "High error rates indicate potential problems, such as misconfigurations, network issues, or failing components in the control plane, which can impact the performance or availability of the cluster.\nLow error rates suggest that the API server is handling requests effectively, with minimal issues.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"data-k8s-api-server\", instance=~\"$instance\", code=~\"[45]..\"}[5m]))*100/sum(rate(apiserver_request_total{job=\"data-k8s-api-server\", instance=~\"$instance\",}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue Additions Rate",
     "type": "timeseries",
     "description": "High values suggest that many tasks are being queued, which could indicate normal cluster activity (e.g., scaling, pod creation) or potential congestion if the workqueue is overloaded.\nLow values indicate fewer tasks being queued, which could mean less activity or that the system is processing tasks efficiently without backlog.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(workqueue_adds_total{job=\"data-k8s-api-server\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "description": "It measures how big the workqueue is.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "workqueue_depth{job=\"data-k8s-api-server\", instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}