{
 "title": "CAdvisor",
 "tags": [
  "cadvisor",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({job=\"data-k8s-cadvisor\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values({job=\"data-k8s-cadvisor\", namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg(\n  sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod)\n  /\n  sum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod)\n  * 100\n) by (pod)\nand \nsum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod) > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"} / 100000",
     "legendFormat": "{{pod}}"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Container CPU Limit",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_spec_cpu_quota{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"} / 100000) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(\n  sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod)\n  /\n  sum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod)\n  * 100\n) by (pod)\nand \nsum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(\n  sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container)\n  /\n  sum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container)\n  * 100\n) by (container)\nand \nsum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container) > 0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Limit",
   "type": "stat",
   "gridPos": { "h": 18, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container) > 0\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod BLKIO Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container BLKIO Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}[5m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device BLKIO Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}[5m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "receive - {{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "transmit - {{pod}}"
    }
   ]
  },
  {
   "title": "Interface Network Traffic",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", interface!~\"lxc.*\"}[5m])) by (interface)",
     "legendFormat": "receive - {{interface}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", interface!~\"lxc.*\"}[5m])) by (interface)",
     "legendFormat": "transmit - {{interface}}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", interface=~\"lxc.*\"}[5m]))",
     "legendFormat": "receive - lxc.*"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", interface=~\"lxc.*\"}[5m]))",
     "legendFormat": "transmit - lxc.*"
    }
   ]
  },
  {
   "title": "Workload Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(\n  sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod)\n  /\n  sum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod)\n  * 100\n) by (pod)\nand \nsum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container Memory Limit",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container) > 0\n",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(\n  sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container)\n  /\n  sum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container)\n  * 100\n) by (container)\nand\nsum(container_spec_memory_limit_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container) > 0\n",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization by Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "container_spec_cpu_quota{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"} / 100000",
       "legendFormat": "{{pod}}"
      },
      { "expression": "$A / $B", "type": "math" }
     ]
    },
    {
     "title": "CPU Utilization by Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "$A / $B", "type": "math" }
     ]
    },
    {
     "title": "CPU Limit by Container",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_spec_cpu_quota{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"} / 100000) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Total CPU Usage per Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total CPU Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 34 },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "User CPU Usage per Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(container_cpu_user_seconds_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "User CPU Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 43 },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_user_seconds_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "System CPU Usage per Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "rate(container_cpu_system_seconds_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "System CPU Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 52 },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_system_seconds_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CPU Throttling Rate by Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(rate(container_cpu_cfs_throttled_periods_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m]) / rate(container_cpu_cfs_periods_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])) * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Throttling Rate by Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((rate(container_cpu_cfs_throttled_periods_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m]) / rate(container_cpu_cfs_periods_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])) * 100) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Average CPU Throttled Time per Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m]) / rate(container_cpu_cfs_throttled_periods_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average CPU Throttled Time per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m]) / rate(container_cpu_cfs_throttled_periods_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", id=~\"(.*)cri-containerd(.*)\"}[1m])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total BLKIO Usage Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total BLKIO Usage Per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\"}[5m])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total BLKIO Usage Per Device",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}[5m])) by (device)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read vs. Write BLKIO Usage Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", operation=\"Read\"}[5m])) by (pod)",
       "legendFormat": "read - {{pod}}"
      },
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\", operation=\"Write\"}[5m])) by (pod)",
       "legendFormat": "write - {{pod}}"
      }
     ]
    },
    {
     "title": "Read vs. Write BLKIO Usage Per Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\",operation=\"Read\"}[5m])) by (container)",
       "legendFormat": "read - {{container}}"
      },
      {
       "expr": "sum(rate(container_blkio_device_usage_total{job=\"data-k8s-cadvisor\", container=~\"$app.*\", container=~\".+\", namespace=~\"$namespace\",operation=\"Write\"}[5m])) by (container)",
       "legendFormat": "write - {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Transmitted Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{job=\"data-k8s-cadvisor\", pod=~\"$app.*\", pod=~\".+\", namespace=~\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}