{
 "title": "CoreDNS",
 "description": "Used Jobs:\n- \"data-k8s-coredns\"",
 "tags": [
  "kubernetes",
  "coredns"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number of CoreDNS Replicas Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(coredns_build_info{job=\"data-k8s-coredns\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Percentile of CoreDNS Request Latency by Instance",
   "type": "stat",
   "description": "High values indicate that a small percentage of DNS requests are experiencing significant delays, which could signal performance issues, network congestion, or overloaded CoreDNS instances.\nLow values suggest that DNS queries are being resolved quickly, which is critical for the overall health and performance of Kubernetes applications and services.",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"data-k8s-coredns\"}[2m])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Rate of CoreDNS Response Codes by RCode",
   "type": "timeseries",
   "description": "High values for successful response codes (e.g., NOERROR) indicate that DNS queries are being resolved correctly and efficiently.\nHigh values for error response codes (e.g., SERVFAIL, NXDOMAIN) may signal issues with DNS resolution, potentially indicating misconfigurations or service disruptions.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{job=\"data-k8s-coredns\"}[2m])) by (rcode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of CoreDNS Response Codes by Instance",
   "type": "timeseries",
   "description": "High values for successful response codes (e.g., NOERROR) indicate that DNS queries are being resolved correctly and efficiently.\nHigh values for error response codes (e.g., SERVFAIL, NXDOMAIN) may signal issues with DNS resolution, potentially indicating misconfigurations or service disruptions.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{job=\"data-k8s-coredns\"}[2m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rate of CoreDNS Requests by Type",
   "type": "timeseries",
   "description": "High values for either request type indicate that a large volume of DNS queries is being made, which may suggest increased application activity or user demand.\nLow values could indicate reduced activity or potential issues with services that rely on DNS resolution.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(sum(rate(coredns_dns_requests_total{job=\"data-k8s-coredns\"}[2m])) by (type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of CoreDNS Requests by Instance",
   "type": "timeseries",
   "description": "High values for either request type indicate that a large volume of DNS queries is being made, which may suggest increased application activity or user demand.\nLow values could indicate reduced activity or potential issues with services that rely on DNS resolution.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(sum(rate(coredns_dns_requests_total{job=\"data-k8s-coredns\"}[2m])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Rate of CoreDNS Cache Hits by Type",
   "type": "timeseries",
   "description": "High values indicate that a significant number of DNS requests are being resolved from the cache, which can lead to improved performance and reduced load on CoreDNS instances.\nLow values may suggest that many requests are not being cached, potentially leading to increased latency and load as queries are resolved through the upstream DNS servers.\n",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{job=\"data-k8s-coredns\"}[2m])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of CoreDNS Cache Hits by Instance",
   "type": "timeseries",
   "description": "High values indicate that a significant number of DNS requests are being resolved from the cache, which can lead to improved performance and reduced load on CoreDNS instances.\nLow values may suggest that many requests are not being cached, potentially leading to increased latency and load as queries are resolved through the upstream DNS servers.\n",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{job=\"data-k8s-coredns\"}[2m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}