{
 "title": "etcd",
 "description": "Used Jobs:\n- \"k8s-etcd\"",
 "tags": [
  "kubernetes",
  "etcd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(etcd_cluster_version,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(etcd_cluster_version{job=\"k8s-etcd\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader Changes Over the Last Hour",
   "type": "stat",
   "description": "Frequent leader changes can be a sign of underlying performance or network issues affecting the stability of the etcd cluster.\n\nHigh values indicate that the etcd cluster is experiencing frequent leader changes, which may lead to instability, delays in responding to requests, or overall degraded cluster performance.\nLow values suggest stable operation of the etcd cluster with minimal leadership disruptions.",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(etcd_server_leader_changes_seen_total{job=\"k8s-etcd\"}[60m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Has A Leader",
   "type": "stat",
   "description": " If the value is 1, then there is a leader in the cluster. On the other hand, if the value is 0, it means there is no leader elected in the cluster. In that case, the etcd would be not operational.",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_server_has_leader{job=\"k8s-etcd\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Proposals Rate Over the Last Hour",
   "type": "stat",
   "description": "High values indicate potential problems in the etcd cluster, such as leader instability or network issues preventing the cluster from committing changes.\nLow or zero values suggest that the cluster is healthy and there are no significant issues with leader elections or quorum loss.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(etcd_server_proposals_failed_total{job=\"k8s-etcd\", instance=~\"$node\"}[60m]))",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Proposals Over 5 Minutes",
   "type": "stat",
   "description": "High values indicate a healthy etcd cluster that is actively committing changes and functioning normally. Increased activity can be expected during operations like deployments or scaling.\nLow values may suggest reduced activity or issues with the cluster’s ability to commit proposals, potentially signaling performance problems or an unhealthy node.",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_committed_total{job=\"k8s-etcd\", instance=~\"$node\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(etcd_server_proposals_applied_total{job=\"k8s-etcd\", instance=~\"$node\"})",
     "legendFormat": "Applied"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{job=\"k8s-etcd\", instance=~\"$node\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Pending Proposals Over 5 Minutes by Instance",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "increase(etcd_server_proposals_pending{job=\"k8s-etcd\", instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commited Proposals Over 5 Minutes by Instance",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(etcd_server_proposals_committed_total{job=\"k8s-etcd\", instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Applied Proposals Over 5 Minutes by Instance",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "increase(etcd_server_proposals_applied_total{job=\"k8s-etcd\", instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "95th Percentile of etcd WAL Fsync Latency",
   "type": "timeseries",
   "description": "High latency (above a few milliseconds) could mean your disk is slow or overloaded, potentially impacting etcd’s ability to keep up with requests.\nLow latency indicates healthy disk performance, ensuring etcd can write to the disk efficiently and respond quickly to Kubernetes operations.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"k8s-etcd\", instance=~\"$node\"}[$__rate_interval])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Percentile of etcd Backend Commit Latency",
   "type": "timeseries",
   "description": "High latency (above a few milliseconds) indicates that the commit process is slow, which may signal disk performance issues or high load on the etcd node. This could eventually lead to slower responses to Kubernetes operations.\nLow latency shows that the commit process is fast and the disk is performing well.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"k8s-etcd\", instance=~\"$node\"}[5m])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "99th Percentile of etcd Network Peer Round-Trip Time",
   "type": "timeseries",
   "description": "High latency (greater than 50ms) could indicate network issues, which may affect the synchronization between etcd members. Over time, this can lead to delayed requests, cluster instability, or even loss of quorum.\nLow latency (under 50ms) shows healthy network performance, ensuring smooth replication and communication between etcd nodes.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job=\"k8s-etcd\", instance=~\"$node\"}[5m])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of etcd Network Peer Sent Failures",
   "type": "stat",
   "description": "High failure rates indicate potential network disruptions or performance bottlenecks in the etcd cluster, which could lead to communication breakdowns between nodes, affecting cluster stability.\nLow or zero failure rates show that communication between etcd members is functioning correctly, ensuring smooth replication and node synchronization.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_sent_failures_total{job=\"k8s-etcd\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}