{
 "title": "Kubelet",
 "description": "Used Jobs:\n- \"k8s-kubelet\"",
 "tags": [
  "kubernetes",
  "kubelet"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kubelet_node_name,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Kubelets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_node_name{job=\"k8s-kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\",job=\"kube-state-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Difference Per Plugin",
   "type": "stat",
   "description": "sum(desired_state_of_world - actual_state_of_world) by (plugin_name)",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(volume_manager_total_volumes{job=\"k8s-kubelet\",state=\"actual_state_of_world\"} - volume_manager_total_volumes{job=\"k8s-kubelet\",state=\"actual_state_of_world\"}) by (plugin_name), \"plugin_name\", \"$1\", \"plugin_name\", \"kubernetes\\\\.io/(.*)\")",
     "legendFormat": "{{plugin_name}}"
    }
   ]
  },
  {
   "title": "Volume Difference Per Instance",
   "type": "stat",
   "description": "sum(desired_state_of_world - actual_state_of_world) by (instance)",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(volume_manager_total_volumes{job=\"k8s-kubelet\",state=\"actual_state_of_world\"} - volume_manager_total_volumes{job=\"k8s-kubelet\",state=\"actual_state_of_world\"}) by (instance), \"plugin_name\", \"$1\", \"plugin_name\", \"kubernetes\\\\.io/(.*)\")",
     "legendFormat": "{{plugin_name}}"
    }
   ]
  },
  {
   "title": "Pods Per Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kubelet_running_pods{job=\"k8s-kubelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Nodes Pods/Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{job=\"k8s-kubelet\", instance=~\".*-worker.*\"})",
     "legendFormat": "Pods"
    },
    {
     "expr": "sum(kubelet_running_containers{job=\"k8s-kubelet\", container_state=\"running\", instance=~\".*-worker.*\"})",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "Master Nodes Pods/Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{job=\"k8s-kubelet\", instance=~\".*-master.*\"})",
     "legendFormat": "Pods"
    },
    {
     "expr": "sum(kubelet_running_containers{job=\"k8s-kubelet\", container_state=\"running\", instance=~\".*-master.*\"})",
     "legendFormat": "Containers"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Running Containers Per Node",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{job=\"k8s-kubelet\", container_state=\"running\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Exited Containers Per Node",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{job=\"k8s-kubelet\", instance=~\"$node\", container_state=\"exited\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Created Containers Per Node",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{job=\"k8s-kubelet\", instance=~\"$node\", container_state=\"created\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runtime Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runtime Operations by Operation Type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(kubelet_runtime_operations_total{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (operation_type)",
       "legendFormat": "{{operation_type}}"
      }
     ]
    },
    {
     "title": "Runtime Operations by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(kubelet_runtime_operations_total{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance)",
       "legendFormat": "{{operation_type}}"
      }
     ]
    },
    {
     "title": "Operation Error Rate by Operation Type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (operation_type)",
       "legendFormat": "{{operation_type}}"
      }
     ]
    },
    {
     "title": "Operation Error Rate by Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance)",
       "legendFormat": "{{operation_type}}"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubelet Operation Durations by operation type",
     "type": "timeseries",
     "description": " It tracks how long different Kubelet operations take and shows the slowest 1% of operations by type.\nThis helps identify which operations are taking the longest in your Kubernetes cluster.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (operation_type, le))",
       "legendFormat": "{{operation_type}}"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubelet Operation Durations by Instance",
     "type": "timeseries",
     "description": "It tracks how long Kubelet operations take and shows the slowest 1% of operations per instance. This helps identify which nodes have the slowest operations in your Kubernetes cluster.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance, le))",
       "legendFormat": "{{operation_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Start Rate & Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration Rate of Kubelet Pod Worker Operations by Operation Type",
     "type": "timeseries",
     "description": "This metric helps in understanding the distribution of different types of Pod operations and can reveal patterns or anomalies in how the kubelet is managing Pods.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "avg(rate(kubelet_pod_worker_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (operation_type)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Duration Rate of Kubelet Pod Worker Operations by Instance",
     "type": "timeseries",
     "description": "By monitoring this metric, you can assess the frequency of Pod operations across different kubelet instances, which helps in identifying any anomalies or performance issues related to Pod management.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "avg(rate(kubelet_pod_worker_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "95th Percentile Pod Start Duration by Instance",
     "type": "timeseries",
     "description": "This metric calculates the 95th percentile of the duration from when a Kubelet first sees a Pod until the Pod begins running.A low 95th percentile pod start duration indicates that even the slowest 5% of pods start quickly. This generally suggests a healthy and well-performing cluster. For instance, a 95th percentile duration of under 30 seconds might indicate that your cluster is in good shape, with most pods starting quickly and efficiently. A high 95th percentile duration indicates that the slowest 5% of pods are taking significantly longer to start. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,sum(rate(kubelet_pod_start_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[$__rate_interval])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Pod Startup Time by Instance",
     "type": "timeseries",
     "description": "This query calculates the average duration it takes for pods to start on each Kubernetes node. The result shows the average pod startup time for each node, allowing you to compare node performance and identify any nodes with slower pod startup times.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "avg(rate(kubelet_pod_start_duration_seconds_sum{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Operation Duration Rate by Operation Type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(rate(storage_operation_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (operation_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Operation Rate Duration by Instance",
     "type": "timeseries",
     "description": "It gives an overview of the types of operations, their success or failure status, and the volume plugins involved.\n\nIt helps you monitor how frequently storage operations are being performed and identify trends or potential issues with specific operations, statuses, or volume plugins. A high rate indicates a large number of storage operations, which could signify heavy load on the storage system. A low rate may suggest fewer storage interactions, which might be normal or signal underutilization.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(rate(storage_operation_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Operation Duration Rate by Volume Plugin",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "label_replace(sum(rate(storage_operation_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (volume_plugin), \"plugin_name\", \"$1\", \"volume_plugin\", \"kubernetes\\\\.io/(.*)\")",
       "legendFormat": "{{plugin_name}}"
      }
     ]
    },
    {
     "title": "Storage Operation Duration Rate by Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(storage_operation_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Storage Operation Duration by Operation Type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (operation_name, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Storage Operation Duration by Instance",
     "type": "timeseries",
     "description": " It is useful for identifying outliers and detecting any slow operations that could impact system performance.\n\nA high value indicates that 99% of operations are faster than this duration, which could suggest performance bottlenecks or inefficiencies in storage. A low value, on the other hand, suggests quick and efficient storage operations.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Storage Operation Duration by Volume Plugin",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "label_replace(histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (volume_plugin, le)), \"volume_plugin\", \"$1\", \"volume_plugin\", \"kubernetes\\\\.io/(.*)\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Storage Operation Duration by Instance",
     "type": "stat",
     "description": " It is useful for identifying outliers and detecting any slow operations that could impact system performance.\n\nA high value indicates that 99% of operations are faster than this duration, which could suggest performance bottlenecks or inefficiencies in storage. A low value, on the other hand, suggests quick and efficient storage operations.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (status, le))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CGroup Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "99th Percentile of Kubelet Cgroup Manager Operation Duration by Operation Type",
     "type": "timeseries",
     "description": "It helps identify how long the slowest 1% of cgroup manager operations take, which is useful for detecting potential performance issues.\n\nA high value indicates that some operations are taking significantly longer than usual, potentially causing delays in managing cgroups. A low value means that most operations are completing quickly, which is ideal for efficient cgroup management.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (operation_type, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubelet Cgroup Manager Operation Duration by Instance",
     "type": "timeseries",
     "description": "It helps identify how long the slowest 1% of cgroup manager operations take, which is useful for detecting potential performance issues.\n\nA high value indicates that some operations are taking significantly longer than usual, potentially causing delays in managing cgroups. A low value means that most operations are completing quickly, which is ideal for efficient cgroup management.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Kubelet Cgroup Manager Operations by Operation Type",
     "type": "timeseries",
     "description": "It helps monitor the frequency of each type of cgroup manager operation, providing insight into how active each operation type is.\n\nA high value for a specific operation type indicates frequent occurrences of that type, which could suggest high activity or potential issues. A low value means that operation is occurring less frequently, which may reflect stable cgroup management or lower activity in that area.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(kubelet_cgroup_manager_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (operation_type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Kubelet Cgroup Manager Operations by Instance",
     "type": "timeseries",
     "description": "It helps track how frequently these operations occur, providing insight into the activity level of the cgroup manager.\n\nA high value indicates that many operations are being performed, which might suggest high activity or potential issues with frequent cgroup adjustments. A low value means fewer ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(kubelet_cgroup_manager_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PLEG",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "99th Percentile of Kubelet PLEG Relisting Duration",
     "type": "timeseries",
     "description": "It helps gauge the maximum time taken by the PLEG process in the top 1% of cases. A high value indicates that the PLEG process is experiencing delays in relisting pods, which might impact cluster performance. A low value signifies that the PLEG relisting is generally efficient.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "99th Percentile of Kubelet PLEG Relisting Interval",
     "type": "timeseries",
     "description": "It helps you understand the upper boundary of how long the PLEG relisting operations are taking. A high value indicates that the PLEG relisting is taking longer than usual, which might signal performance issues or delays in Kubelet operations. A low value suggests that the relisting is occurring promptly, indicating good performance.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_interval_seconds_bucket{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kubelet PLEG Relist Operation Rate",
     "type": "stat",
     "description": "A high rate of relisting operations might indicate frequent changes or issues with the pods, such as frequent pod restarts, deployments, or other disruptions. This could lead to increased kubelet overhead and potential performance degradation.\nA low rate of relisting operations typically indicates that the kubelet is stable and there are fewer changes in the pod states. This is usually a sign of a stable and healthy cluster.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(kubelet_pleg_relist_duration_seconds_count{job=\"k8s-kubelet\", instance=~\"$node\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}