{
 "title": "Kube Controller Manager",
 "description": "Used Jobs:\n- \"k8s-kube-controller-manager\"",
 "tags": [
  "kubernetes",
  "kube-controller-manager"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "99th Percentile Work Queue Duration for Kube-Controller-Manager by Name",
   "type": "timeseries",
   "description": "A high value indicates that the kube-controller-manager is taking longer to fulfill requests, potentially signaling performance bottlenecks or a backlog of tasks. A low value suggests that the controller is efficiently processing its queue, maintaining the cluster's desired state in a timely manner. Monitoring this can help identify delays in cluster operations and inform scaling or optimization efforts.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(workqueue_queue_duration_seconds_bucket{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (name, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Percentile Work Queue Duration for Kube-Controller-Manager by Instance",
   "type": "timeseries",
   "description": "A high value indicates that the kube-controller-manager is taking longer to fulfill requests, potentially signaling performance bottlenecks or a backlog of tasks. A low value suggests that the controller is efficiently processing its queue, maintaining the cluster's desired state in a timely manner. Monitoring this can help identify delays in cluster operations and inform scaling or optimization efforts.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(workqueue_queue_duration_seconds_bucket{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Workqueue Additions Rate by Name",
   "type": "timeseries",
   "description": "It helps monitor the load on your workqueues; a high value could indicate that a node is handling a large number of tasks, which might suggest potential issues or increased workload. Conversely, a low value indicates that the node is handling fewer tasks, which is generally preferable if tasks are being processed efficiently.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (name)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Workqueue Additions Rate by Instance",
   "type": "timeseries",
   "description": "It helps monitor the load on your workqueues; a high value could indicate that a node is handling a large number of tasks, which might suggest potential issues or increased workload. Conversely, a low value indicates that the node is handling fewer tasks, which is generally preferable if tasks are being processed efficiently.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth by Name",
   "type": "timeseries",
   "description": "By tracking the workqueue depth, you can gauge how many actions are pending processing. A low value indicates that the controller manager is keeping up with its tasks efficiently, while a high value or increasing trend suggests that the controller manager may be overloaded or facing issues, potentially leading to delays or performance problems in your Kubernetes cluster.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (name)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth by Instance",
   "type": "timeseries",
   "description": "By tracking the workqueue depth, you can gauge how many actions are pending processing. A low value indicates that the controller manager is keeping up with its tasks efficiently, while a high value or increasing trend suggests that the controller manager may be overloaded or facing issues, potentially leading to delays or performance problems in your Kubernetes cluster.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "API Request Latency by Method",
   "type": "timeseries",
   "description": "It helps you understand how quickly the API server responds to these requests. A low value indicates that requests are being handled promptly, which is ideal for maintaining efficient cluster operations. Conversely, a high value suggests that there may be delays in processing API requests, which could point to performance issues or bottlenecks in your Kubernetes environment.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (verb, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Latency by Instance",
   "type": "timeseries",
   "description": "It helps you understand how quickly the API server responds to these requests. A low value indicates that requests are being handled promptly, which is ideal for maintaining efficient cluster operations. Conversely, a high value suggests that there may be delays in processing API requests, which could point to performance issues or bottlenecks in your Kubernetes environment.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (instance, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rates by Method",
   "type": "timeseries",
   "description": "This visualization tracks the rate of HTTP requests made by the Kubernetes controller manager.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rates by Instance",
   "type": "timeseries",
   "description": "This visualization tracks the rate of HTTP requests made by the Kubernetes controller manager.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rates by Code",
   "type": "timeseries",
   "description": "This visualization tracks the rate of HTTP requests made by the Kubernetes controller manager, categorized by HTTP response codes. By examining this data, you can assess the health of the API interactions:\n\n2xx (Successful Requests): A high rate indicates that most requests are successfully processed, which is a positive sign of operational efficiency.\n3xx (Redirection Responses): A higher rate may indicate redirections or changes in resource locations, which could impact performance.\n4xx (Client Errors): A high rate of 4xx errors suggests issues with client-side requests, possibly indicating misconfigurations or incorrect API usage.\n5xx (Server Errors): A high rate of 5xx errors points to server-side problems, potentially affecting the stability and reliability of the API server.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\",code=~\"2..\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\",code=~\"3..\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\",code=~\"4..\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\",code=~\"5..\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  { "title": "Process Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Low Value: Indicates that the controller manager is using minimal CPU resources, which generally means it's operating efficiently and not under heavy load.\nHigh Value: Suggests that the controller manager is consuming significant CPU resources, which could point to high workload, potential inefficiencies, or performance issues.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "timeseries",
   "description": "Low Value: Indicates that the controller manager is using minimal resident memory, which typically means efficient memory usage and a lower likelihood of memory-related issues.\nHigh Value: Suggests that the controller manager is consuming a large amount of memory, which may point to potential memory leaks, inefficient processes, or increased workload.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"k8s-kube-controller-manager\", instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}