{
 "title": "Node",
 "description": "Used Jobs:\n- \"harbor-node-exporter\"",
 "tags": [
  "node-exporter",
  "harbor"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"harbor-node-exporter\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_pressure_cpu_waiting_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(irate(node_pressure_memory_waiting_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Mem"
    },
    {
     "expr": "avg(irate(node_pressure_io_waiting_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"idle\"}[5m])) * 100))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - ((node_memory_MemAvailable_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}) / (node_memory_MemTotal_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_filesystem_avail_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"}))",
     "legendFormat": "Root"
    }
   ]
  },
  {
   "title": "Traffic Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"harbor-node-exporter\", instance=~\"$instance\"} - node_boot_time_seconds{job=\"harbor-node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"idle\"}[5m])) * 100 )",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Utilization by Mode",
     "type": "timeseries",
     "description": "System - Processes executing in kernel mode\nUser - Normal processes executing in user mode\nNice - Niced processes executing in user mode\nIOWait - Waiting for I/O to complete\nIRQ - Servicing interrupts\nSoftIRQ - Servicing softirqs\nSteal - Time spent in other operating systems when running in a virtualized environment\nIdle - Waiting for something to happen",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"system\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"user\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "User"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"nice\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "Nice"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=~\"iowait\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "IOWait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=~\"irq\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "IRQ"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"softirq\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "SoftIRQ"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"steal\"}[$__rate_interval])) /\r\nscalar(count(count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}) by (cpu)))",
       "legendFormat": "Steal"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"idle\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU Utilization",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\", mode=\"idle\"}[5m])) * 100))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "System Load Average 1 minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{job=\"harbor-node-exporter\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU some by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_pressure_cpu_waiting_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "System Load Average 1 minute",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load1{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average CPU some",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(node_pressure_cpu_waiting_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Context Switches by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_context_switches_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Interrupts by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_intr_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Context Switch",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(irate(node_context_switches_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Interrupt",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(irate(node_intr_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Schedule timeslices executed by each cpu",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_schedstat_timeslices_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "CPU time spent in user and system contexts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average CPU time spent in user and system contexts",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(irate(process_cpu_seconds_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization Per Node",
     "type": "stat",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - ((node_memory_MemAvailable_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}) / (node_memory_MemTotal_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(node_memory_MemTotal_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(node_memory_MemAvailable_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Average Memory Utilization",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((1 - ((node_memory_MemAvailable_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}) / (node_memory_MemTotal_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "timeseries",
     "description": "Apps - Memory used by user-space applications\n\nPageTables - Memory used to map between virtual and physical memory addresses\n\nSwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified\n\nSlab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)\n\nCache - Parked file data (file content) cache\n\nBuffers - Block device (e.g. harddisk) cache\n\nUnused - Free memory unassigned\n\nSwap - Swap space used\n\nHardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"} - node_memory_MemFree_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"} - node_memory_Buffers_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"} - node_memory_Cached_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"} - node_memory_Slab_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"} - node_memory_PageTables_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"} - node_memory_SwapCached_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Apps"
      },
      {
       "expr": "avg((node_memory_PageTables_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "PageTables"
      },
      {
       "expr": "avg(node_memory_SwapCached_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "SwapCache"
      },
      {
       "expr": "avg((node_memory_Slab_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Slab"
      },
      {
       "expr": "avg((node_memory_Cached_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Cache"
      },
      {
       "expr": "avg((node_memory_Buffers_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Buffers"
      },
      {
       "expr": "avg((node_memory_MemFree_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Unused"
      },
      {
       "expr": "avg((node_memory_SwapTotal_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"} - node_memory_SwapFree_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Swap"
      },
      {
       "expr": "avg((node_memory_HardwareCorrupted_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"}))",
       "legendFormat": "Hardware Corrupted"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive Detail",
     "type": "timeseries",
     "description": "Inactive_file - File-backed memory on inactive LRU list\n\nInactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)\n\nActive_file - File-backed memory on active LRU list\n\nActive_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_Inactive_file_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Inactive_file"
      },
      {
       "expr": "sum(node_memory_Inactive_anon_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Inactive_anon"
      },
      {
       "expr": "sum(node_memory_Active_file_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Active_file"
      },
      {
       "expr": "sum(node_memory_Active_anon_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Active_anon"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive",
     "type": "stat",
     "description": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes\n\nActive - Memory that has been used more recently and usually not reclaimed unless absolutely necessary",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_Inactive_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Inactive"
      },
      {
       "expr": "sum(node_memory_Active_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Active"
      }
     ]
    },
    {
     "title": "Memory Committed",
     "type": "stat",
     "description": "Committed_AS - Amount of memory presently allocated on the system\n\nCommitLimit - Amount of  memory currently available to be allocated on the system",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_Committed_AS_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Committed_AS"
      },
      {
       "expr": "sum(node_memory_CommitLimit_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "CommitLimit"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "timeseries",
     "description": "Writeback - Memory which is actively being written back to disk\n\nWritebackTmp - Memory used by FUSE for temporary writeback buffers\n\nDirty - Memory which is waiting to get written back to the disk",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_Writeback_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Writeback"
      },
      {
       "expr": "sum(node_memory_WritebackTmp_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "WritebackTmp"
      },
      {
       "expr": "sum(node_memory_Dirty_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\"})",
       "legendFormat": "Dirty"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Root Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"} * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Root Disk Space",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"harbor-node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes by Device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device!~\"veth.*\"}[$__rate_interval]) * 8) by (device)",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device!~\"veth.*\"}[$__rate_interval]) * 8) by (device)",
       "legendFormat": "{{device}} - Transmit"
      },
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device=~\"veth.*\"}[$__rate_interval]) * 8) ",
       "legendFormat": "veth* - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device=~\"veth.*\"}[$__rate_interval]) * 8) ",
       "legendFormat": "veth* - Transmit"
      }
     ]
    },
    {
     "title": "Bytes by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "{{instance}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "{{instance}} - Transmit"
      }
     ]
    },
    {
     "title": "Total Bytes",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Packets by Device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_packets_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device!~\"veth.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device!~\"veth.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Transmit"
      },
      {
       "expr": "sum(irate(node_network_receive_packets_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device=~\"veth.*\"}[$__rate_interval]))",
       "legendFormat": "veth* - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device=~\"veth.*\"}[$__rate_interval]))",
       "legendFormat": "veth* - Transmit"
      }
     ]
    },
    {
     "title": "Packets by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_packets_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Transmit"
      }
     ]
    },
    {
     "title": "Total Packets",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_packets_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_packets_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Packet Error by Device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_errs_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device!~\"veth.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "sum(irate(node_network_transmit_errs_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device!~\"veth.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Transmit errors"
      },
      {
       "expr": "sum(irate(node_network_receive_errs_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device=~\"veth.*\"}[$__rate_interval]))",
       "legendFormat": "veth* - Receive errors"
      },
      {
       "expr": "sum(irate(node_network_transmit_errs_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device=~\"veth.*\"}[$__rate_interval]))",
       "legendFormat": "veth* - Transmit errors"
      }
     ]
    },
    {
     "title": "Packet Error by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_errs_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Receive errors"
      },
      {
       "expr": "sum(irate(node_network_transmit_errs_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Transmit errors"
      }
     ]
    },
    {
     "title": "Total Packet Error",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_errs_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_errs_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Packet Drop by Device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_drop_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device!~\"veth.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device!~\"veth.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Transmit drop"
      },
      {
       "expr": "sum(irate(node_network_receive_drop_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device=~\"veth.*\"}[$__rate_interval]))",
       "legendFormat": "veth* - Receive drop"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{job=\"harbor-node-exporter\", instance=~\"$instance\", device=~\"veth.*\"}[$__rate_interval]))",
       "legendFormat": "veth* - Transmit drop"
      }
     ]
    },
    {
     "title": "Packet Drop by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_drop_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Receive drop"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Total Packet Drop",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_drop_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{job=\"harbor-node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Transmit"
      }
     ]
    }
   ]
  }
 ]
}