{
 "title": "CoreDNS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values({job=~\"data-coredns-log-exporter\"},domain)"
    }
   },
   {
    "name": "subdomain",
    "label": "Sub-Domain",
    "query": {
     "query": "label_values({job=~\"data-coredns-log-exporter\", domain=~\"(.*).$domain.\"},domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(coredns_duration_seconds{domain=~\"$subdomain\"}) by (domain)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Count per Domain",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "count(count_over_time(coredns_duration_seconds{domain=~\"$subdomain\"}[$__interval])) by (domain)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Query Duration by Request Type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(coredns_duration_seconds{domain=~\"$subdomain\"}) by (reqtype)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Query Duration by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(coredns_duration_seconds{domain=~\"$subdomain\"}) by (rescode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DNS Requests by Instance:Zone:Type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{domain=~\"$subdomain\", proto=~\"udp\"}[$__rate_interval])) by (proto, instance, type, zone) > 0",
     "legendFormat": "{{ instance }}:{{ zone }}:{{ type }}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{domain=~\"$subdomain\", proto=~\"tcp\"}[$__rate_interval])) by (proto, instance, type, zone) > 0",
     "legendFormat": "{{ instance }}:{{ zone }}:{{ type }}"
    }
   ]
  }
 ]
}