{
 "title": "Database",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(mysql_global_status_busy_time,instance)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mysql_global_status_busy_time{instance=~\"$group.*\"},instance)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values(mysql_info_schema_table_rows{instance=~\"$instance\"},schema)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Subquery Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_subquery_cache_hit{instance=~\"$instance\"}[30s]) / \n(rate(mysql_global_status_subquery_cache_hit{instance=~\"$instance\"}[30s]) + rate(mysql_global_status_subquery_cache_miss{instance=~\"$instance\"}[30s])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hits Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_subquery_cache_hit{instance=~\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss Ratio Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_subquery_cache_hit{instance=~\"$instance\"}[30s])) \n/ (sum(rate(mysql_global_status_subquery_cache_hit{instance=~\"$instance\"}[30s])) + sum(rate(mysql_global_status_subquery_cache_miss{instance=~\"$instance\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subquery Cache Hits & Misses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_subquery_cache_hit{instance=~\"$instance\"}[30s]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(rate(mysql_global_status_subquery_cache_miss{instance=~\"$instance\"}[30s]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Size by Schema:Table (Data + Index)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(mysql_info_schema_table_size{instance=~\"$instance\", schema=~\"$schema\", component!~\"data_free\"}) by (schema, table) > 0",
       "legendFormat": "{{schema}}:{{table}}"
      }
     ]
    },
    {
     "title": "Rows Read Rate by Schema:Table",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mysql_info_schema_table_statistics_rows_read_total{instance=~\"$instance\", schema=~\"$schema\"}[30s])) by (schema, table) > 0",
       "legendFormat": "{{schema}}:{{table}}"
      }
     ]
    },
    {
     "title": "Table Size",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mysql_info_schema_table_size{instance=~\"$instance\", schema=~\"$schema\", component!~\"data_free\"} > 0) by (component)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(mysql_info_schema_table_size{instance=~\"$instance\", schema=~\"$schema\", component!~\"data_free\"} > 0)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Total Rows Read",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(mysql_info_schema_table_statistics_rows_read_total{instance=~\"$instance\", schema=~\"$schema\"}[30s])) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rows Changed Rate by Schema:Table",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mysql_info_schema_table_statistics_rows_changed_total{instance=~\"$instance\", schema=~\"$schema\"}[30s])) by (schema, table) > 0",
       "legendFormat": "{{schema}}:{{table}}"
      }
     ]
    },
    {
     "title": "Rows * Indexes Changed Rate by Schema:Table",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mysql_info_schema_table_statistics_rows_changed_x_indexes_total{instance=~\"$instance\", schema=~\"$schema\"}[30s])) by (schema, table) > 0",
       "legendFormat": "{{schema}}:{{table}}"
      }
     ]
    },
    {
     "title": "Total Rows Changed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(mysql_info_schema_table_statistics_rows_changed_total{instance=~\"$instance\", schema=~\"$schema\"}[30s])) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Rows * Indexes Changed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(mysql_info_schema_table_statistics_rows_changed_x_indexes_total{instance=~\"$instance\", schema=~\"$schema\"}[30s])) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "InnoDB Compression",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compression Level",
     "type": "stat",
     "description": "The level of zlib compression to use for InnoDB compressed tables and indexes.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_variables_innodb_compression_level{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compression Failure Threshold",
     "type": "stat",
     "description": "The compression failure rate threshold for a table",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_variables_innodb_compression_failure_threshold_pct{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compression Failure Rate Threshold",
     "type": "stat",
     "description": "The maximum percentage that can be reserved as free space within each compressed page, allowing room to reorganize the data and modification log within the page when a compressed table or index is updated and the data might be recompressed.",
     "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_variables_innodb_compression_pad_pct_max{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Pages to The Redo Log",
     "type": "stat",
     "description": "Specifies whether images of re-compressed pages are written to the redo log. Re-compression may occur when changes are made to compressed data.",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_variables_innodb_log_compressed_pages{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compress Attempts by Page Size",
     "type": "timeseries",
     "description": "Number of compression operations attempted. Pages are compressed whenever an empty page is created or the space for the uncompressed modification log runs out.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "rate(mysql_info_schema_innodb_cmp_compress_ops_total{instance=~\"$instance\"}[$__interval]) or irate(mysql_info_schema_innodb_cmp_compress_ops_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "{{page_size}}"
      }
     ]
    },
    {
     "title": "Uncompressed Attempts by Page Size",
     "type": "timeseries",
     "description": "Number of uncompression operations performed. Compressed InnoDB pages are uncompressed whenever compression fails, or the first time a compressed page is accessed in the buffer pool and the uncompressed page does not exist.",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 5 },
     "targets": [
      {
       "expr": "rate(mysql_info_schema_innodb_cmp_uncompress_ops_total{instance=~\"$instance\"}[$__interval]) or irate(mysql_info_schema_innodb_cmp_uncompress_ops_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "{{page_size}}"
      }
     ]
    },
    {
     "title": "Compression Success Ratio by Page Size",
     "type": "timeseries",
     "description": "Shows the ratio between Success InnoDB Compress vs the total InnoDB Compress operations. A high ration indicates that InnoDB compression is being effective and helping to save disk space.",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 14 },
     "targets": [
      {
       "expr": "sum_over_time(mysql_info_schema_innodb_cmp_compress_ops_ok_total{instance=~\"$instance\"}[$__interval]) / sum_over_time(mysql_info_schema_innodb_cmp_compress_ops_total{instance=~\"$instance\"}[$__interval]) or sum_over_time(mysql_info_schema_innodb_cmp_compress_ops_ok_total{instance=~\"$instance\"}[5m]) / sum_over_time(mysql_info_schema_innodb_cmp_compress_ops_total{instance=~\"$instance\"}[5m]) ",
       "legendFormat": "{{page_size}}"
      }
     ]
    }
   ]
  }
 ]
}