{
 "title": "HAProxy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(haproxy_server_status,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"haproxy-$group-haproxy\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic General Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HAProxy Backend Connection Time (Average) by Proxy",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_connect_time_average_seconds{instance=~\"$instance\"}) by (proxy)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HAProxy Backend Connection Time (Average) by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_connect_time_average_seconds{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HAProxy Backend Connection Time (Average)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_connect_time_average_seconds{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HAProxy Backend Response Time (Average) by Proxy",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_response_time_average_seconds{instance=~\"$instance\"}) by (proxy)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HAProxy Backend Response Time (Average) by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_connect_time_average_seconds{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HAProxy Backend Response Time (Average) by Instance",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_connect_time_average_seconds{instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "All HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_responses_total{instance=~\"$instance\"}[$__rate_interval])) by (code)",
       "legendFormat": "front:{{ code }}"
      },
      {
       "expr": "sum(rate(haproxy_backend_http_responses_total{instance=~\"$instance\"}[$__rate_interval])) by (code)",
       "legendFormat": "back:{{ code }}"
      }
     ]
    },
    {
     "title": "Incoming / Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_bytes_in_total{instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "in:front"
      },
      {
       "expr": "sum(rate(haproxy_frontend_bytes_out_total{instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "out:front"
      },
      {
       "expr": "sum(rate(haproxy_backend_bytes_in_total{instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "in:back"
      },
      {
       "expr": "sum(rate(haproxy_backend_bytes_out_total{instance=~\"$instance\"}[$__rate_interval]) * 8)",
       "legendFormat": "out:back"
      }
     ]
    },
    {
     "title": "Number of connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_connections_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "front"
      },
      {
       "expr": "sum(rate(haproxy_backend_connection_errors_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "back"
      }
     ]
    },
    {
     "title": "Requests and Responses",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_requests_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "front requests"
      },
      {
       "expr": "sum(rate(haproxy_frontend_request_errors_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "front requests errors"
      },
      {
       "expr": "sum(rate(haproxy_frontend_requests_denied_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "front request denied"
      },
      {
       "expr": "sum(rate(haproxy_backend_redispatch_warnings_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "back redispatch warnings"
      },
      {
       "expr": "sum(rate(haproxy_backend_retry_warnings_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "back retry warnings"
      },
      {
       "expr": "sum(rate(haproxy_backend_response_errors_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "back response errors"
      },
      {
       "expr": "sum(rate(haproxy_backend_current_queue{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "back queued requests"
      },
      {
       "expr": "sum(rate(haproxy_backend_http_requests_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "back requests"
      }
     ]
    },
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 41 },
     "targets": [
      {
       "expr": "sum(haproxy_frontend_current_sessions{instance=~\"$instance\"})",
       "legendFormat": "front"
      },
      {
       "expr": "sum(haproxy_backend_current_sessions{instance=~\"$instance\"})",
       "legendFormat": "back"
      }
     ]
    }
   ]
  },
  { "title": "Throughput / Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Front - Incoming / Outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{instance=~\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "in:{{ proxy }}"
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{instance=~\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "out:{{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Incoming / Outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{instance=~\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "in:{{ proxy }}"
    },
    {
     "expr": "rate(haproxy_backend_bytes_out_total{instance=~\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "out:{{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - Connections successful / denied",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_connections_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "successful:{{ proxy }}"
    },
    {
     "expr": "rate(haproxy_frontend_denied_connections_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "denied:{{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Connections attempts / errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_connection_attempts_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "attempts:{{ proxy }}"
    },
    {
     "expr": "rate(haproxy_backend_connection_errors_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "error:{{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of connections per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "haproxy_frontend_connections_rate_max{instance=~\"$instance\"}",
     "legendFormat": "max:{{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Connections reuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_connection_reuses_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "reuses:{{ proxy }}"
    }
   ]
  }
 ]
}