{
 "title": "Kafka",
 "tags": [ "kafka" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{job=\"data-kafka-exporter\", topic!~\"_.*\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message in per second by Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$topic\"}) by (topic, consumergroup)",
     "legendFormat": "{{consumergroup}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Total Message in per second",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Total Lag",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$topic\"})",
     "legendFormat": "{{consumergroup}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}