{
 "title": "Kubernetes V2",
 "tags": [
  "cadvisor",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({job=~\"k8s-cadvisor-$cluster\"},kubernetes_io_hostname)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({job=~\"k8s-cadvisor-$cluster\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", instance=~\"$host\", job=~\"k8s-kube-state-metrics-$cluster\"},label_app)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", instance=~\"$host\", job=~\"k8s-kube-state-metrics-$cluster\", pod=~\"$app.*\"},label_app)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$namespace\", job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", pod=~\"$app-$group.*\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(sum(kube_pod_labels{namespace=~\"$namespace\", pod=~\"$app-$group.*\", label_app!~\"\"}) by (pod, label_app)) by (label_app)",
       "legendFormat": "{{label_app}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((time() - container_start_time_seconds{job=~\"k8s-cadvisor-$cluster\", namespace=~\"$namespace\", pod=~\"$app-$group.*\", image!=\"registry.k8s.io/pause:3.9\", container=~\"$container\", container!~\"POD|cronjob|\"}) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\"$app-$group.*\"}\n) by (namespace, label_app, container) < 3600",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((\n  sum(container_memory_working_set_bytes{\n    job=\"k8s-cadvisor-$cluster\",\n    pod=~\"$app-$group.*\",\n    container=~\"$container\", \n    container!~\"POD\", \n    namespace=~\"$namespace\"\n  }) by (pod, container)\n  /\n  sum(kube_pod_container_resource_limits{\n    namespace=~\"$namespace\",\n    pod=~\"$app-$group.*\",\n    resource=\"memory\"\n  }) by (pod, container)\n) * 100\n* on(pod) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\"$app-$group.*\", label_app!~\"\"}\n) by (label_app, container)",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg((sum(rate(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", pod=~\".*$group.*\", pod=~\"$app.*\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", container=~\"$container\", container!~\"^(POD|)$\"}[1m])) by (pod, container)\n/ \nsum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", resource=\"cpu\"}) by (pod, container)) \n* on(pod) group_left(label_app, label_job_name)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", label_app!~\"\"}\n) by (label_app, label_job_name, container)",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg((container_memory_working_set_bytes{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\"$app-$group.*\", container!~\"POD|\", container=~\"$container\"}) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\"$app-$group.*\", label_app!~\"\"}\n) by (namespace, label_app, container)",
       "legendFormat": "usage:{{label_app}}:{{container}}"
      },
      {
       "expr": "avg((kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$app-$group.*\", resource=\"memory\", container=~\"$container\"}) \n* on(pod) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\"$app-$group.*\", label_app!~\"\"}\n) by (label_app, container)",
       "legendFormat": "request:{{label_app}}:{{container}}"
      },
      {
       "expr": "avg((kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$app-$group.*\", resource=\"memory\", container=~\"$container\"}) \n* on(pod) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\"$app-$group.*\", label_app!~\"\"}\n) by (label_app, container)",
       "legendFormat": "limit:{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "avg((sum(rate(container_cpu_usage_seconds_total{pod=~\".*$group.*\", pod=~\"$app.*\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", container!~\"^(POD|)$\", container=~\"$container\"}[1m])) by (pod, container, namespace)) \n* on(pod, namespace) group_left(label_app, label_job_name)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", label_app!~\"\"}\n) by (label_app, label_job_name, container, namespace) * 1000",
       "legendFormat": "usage:{{label_app}}:{{container}}"
      },
      {
       "expr": "avg((kube_pod_container_resource_requests{job=~\"k8s-kube-state-metrics-$cluster\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app(.*)\", resource=\"cpu\", container=~\"$container\"}) \n* on(pod) group_left(label_app)\nkube_pod_labels{job=~\"k8s-kube-state-metrics-$cluster\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", label_app!~\"\"}\n) by (label_app, container) * 1000",
       "legendFormat": "request:{{label_app}}:{{container}}"
      },
      {
       "expr": "avg((kube_pod_container_resource_limits{job=~\"k8s-kube-state-metrics-$cluster\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app(.*)\", resource=\"cpu\", container=~\"$container\"}) \n* on(pod) group_left(label_app)\nkube_pod_labels{job=~\"k8s-kube-state-metrics-$cluster\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", label_app!~\"\"}\n) by (label_app, container) * 1000",
       "legendFormat": "limit:{{label_app}}:{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{job=~\"k8s-kube-state-metrics\", node=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", resource=\"cpu\"}) * count(sum(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", image!=\"registry.k8s.io/pause:3.9\"}) by (pod))",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=~\"k8s-kube-state-metrics\", node=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", resource=\"cpu\"}) * count(sum(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", image!=\"registry.k8s.io/pause:3.9\"}) by (pod))",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", container!~\"^(POD|)$\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=~\"node-exporter\", instance=~\"$cluster:k8s-worker:.*:$host\", mode=\"idle\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{job=~\"k8s-kube-state-metrics\", node=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", resource=\"memory\"}) * count(sum(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", image!=\"registry.k8s.io/pause:3.9\"}) by (pod))",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=~\"k8s-kube-state-metrics\", node=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", resource=\"memory\"}) * count(sum(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", image!=\"registry.k8s.io/pause:3.9\"}) by (pod))",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", container!~\"^(POD|)$\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=~\"$cluster(.*)-node-exporter\", instance=~\"$cluster:k8s-worker:.*:$host\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Pod Network Traffic",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{\n    job=\"k8s-cadvisor-$cluster\",\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    name=~\".+\"\n  }[1m]))",
       "legendFormat": "Transmit"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{\n    job=\"k8s-cadvisor-$cluster\",\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    name=~\".+\"\n  }[1m]))",
       "legendFormat": "Receive"
      }
     ]
    },
    {
     "title": "Container I/O",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{\n    job=\"k8s-cadvisor-$cluster\",\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    container!~\"POD\",\n    name=~\".+\"\n  }[1m]))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{\n    job=\"k8s-cadvisor-$cluster\",\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    container!~\"POD\",\n    name=~\".+\"\n  }[1m]))",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Pods/Containers Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", image!=\"registry.k8s.io/pause:3.9\"}) by (pod))",
       "legendFormat": "Pods"
      },
      {
       "expr": "count(sum(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", container=~\"$container\", image!=\"registry.k8s.io/pause:3.9\"}) by (pod, container))",
       "legendFormat": "Containers"
      }
     ]
    },
    {
     "title": "Pods Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Pods Not Running",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 17, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", phase=~\"Failed\"}) by (phase, pod, namespace) > 0",
       "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
      },
      {
       "expr": "sum(kube_pod_status_phase{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", phase=~\"Pending\"}) by (phase, pod, namespace) > 0",
       "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
      },
      {
       "expr": "sum(kube_pod_status_phase{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", phase=~\"Unknown\"}) by (phase, pod, namespace) > 0",
       "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
      },
      {
       "expr": "sum(kube_pod_status_phase{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", phase=~\"Running|Succeeded\"}) == sum(kube_pod_status_phase{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((time() - container_start_time_seconds{job=~\"k8s-cadvisor-$cluster\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", pod=~\".+\", image!=\"registry.k8s.io/pause:3.9\", container=~\"$container\", container!~\"POD|\"}) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (namespace, label_app, container)",
       "legendFormat": "{{namespace}}:{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((\n  sum(container_memory_working_set_bytes{\n    job=\"k8s-cadvisor-$cluster\",\n    pod=~\"$app-$group.*\",\n    container=~\"$container\", \n    container!~\"POD\", \n    namespace=~\"$namespace\"\n  }) by (pod, container)\n  /\n  sum(kube_pod_container_resource_limits{\n    namespace=~\"$namespace\",\n    pod=~\"$app-$group.*\",\n    resource=\"memory\"\n  }) by (pod, container)\n) * 100\n* on(pod) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\"$app-$group.*\"}\n) by (label_app, container)",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg((sum(rate(container_cpu_usage_seconds_total{job=~\"k8s-cadvisor-$cluster\", pod=~\".*$group.*\", pod=~\"$app.*\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", container=~\"$container\", container!~\"^(POD|)$\"}[1m])) by (pod, container)\n/ \nsum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\", resource=\"cpu\"}) by (pod, container)) \n* on(pod) group_left(label_app, label_job_name)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, label_job_name, container)",
       "legendFormat": "{{label_job_name}}{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "Memory Limit",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((kube_pod_container_resource_limits{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app(.*)\", resource=\"memory\", container=~\"$container\"}) \n* on(pod) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, container)",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "Memory Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((kube_pod_container_resource_requests{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app(.*)\", resource=\"memory\", container=~\"$container\"}) \n* on(pod) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, container)",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg((container_memory_working_set_bytes{job=~\"k8s-cadvisor-$cluster\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\"$app-$group.*\", container!~\"POD|\", container=~\"$container\"}) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\"$app-$group.*\"}\n) by (namespace, label_app, container)",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "avg((sum(rate(container_cpu_usage_seconds_total{pod=~\".*$group.*\", pod=~\"$app.*\", namespace=~\"$namespace\", image!=\"registry.k8s.io/pause:3.9\", container!~\"^(POD|)$\", container=~\"$container\"}[1m])) by (pod, container, namespace)) \n* on(pod, namespace) group_left(label_app, label_job_name)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, label_job_name, container, namespace) * 1000",
       "legendFormat": "{{label_job_name}}{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "CPU Limits",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((kube_pod_container_resource_limits{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app(.*)\", resource=\"cpu\", container=~\"$container\"}) \n* on(pod) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, container) * 1000",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "CPU Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((kube_pod_container_resource_requests{job=~\"k8s-kube-state-metrics\", namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app(.*)\", resource=\"cpu\", container=~\"$container\"}) \n* on(pod) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, container) * 1000",
       "legendFormat": "{{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg((sum(rate(container_network_transmit_bytes_total{\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    namespace=~\"$namespace\",\n    name=~\".+\"\n  }[1m])) by (pod, container, namespace))\n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, container, namespace)",
       "legendFormat": "Transmit: {{label_app}}"
      },
      {
       "expr": "avg((sum(rate(container_network_receive_bytes_total{\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    namespace=~\"$namespace\",\n    name=~\".+\"\n  }[1m])) by (pod, container, namespace))\n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, container, namespace)",
       "legendFormat": "Receive: {{label_app}}"
      }
     ]
    },
    {
     "title": "I/O",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg((sum(rate(container_fs_reads_bytes_total{\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    namespace=~\"$namespace\",\n    container=~\"$container\", \n    container!~\"POD\",\n    name=~\".+\"\n  }[1m])) by (pod, container, namespace)) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, container, namespace)",
       "legendFormat": "Reads: {{label_app}}:{{container}}"
      },
      {
       "expr": "avg((sum(rate(container_fs_writes_bytes_total{\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    namespace=~\"$namespace\",\n    container=~\"$container\", \n    container!~\"POD\",\n    name=~\".+\"\n  }[1m])) by (pod, container, namespace)) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n) by (label_app, container, namespace)",
       "legendFormat": "Writes: {{label_app}}:{{container}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((sum(rate(container_network_transmit_bytes_total{\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    namespace=~\"$namespace\",\n    name=~\".+\"\n  }[1m])) by (pod, container, namespace))\n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n)",
       "legendFormat": "Transmit"
      },
      {
       "expr": "sum((sum(rate(container_network_receive_bytes_total{\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    namespace=~\"$namespace\",\n    name=~\".+\"\n  }[1m])) by (pod, container, namespace))\n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n)",
       "legendFormat": "Receive"
      }
     ]
    },
    {
     "title": "I/O",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((sum(rate(container_fs_reads_bytes_total{\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    namespace=~\"$namespace\",\n    container=~\"$container\", \n    container!~\"POD\",\n    name=~\".+\"\n  }[1m])) by (pod, container, namespace)) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n)",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum((sum(rate(container_fs_writes_bytes_total{\n    pod=~\".*$group.*\",\n    pod=~\"$app.*\",\n    namespace=~\"$namespace\",\n    container=~\"$container\", \n    container!~\"POD\",\n    name=~\".+\"\n  }[1m])) by (pod, container, namespace)) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"$namespace\", pod=~\".*$group.*\", pod=~\"$app.*\"}\n)",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "PVC Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\"}/kubelet_volume_stats_capacity_bytes{job=~\"$cluster-k8s-kubelet\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PVC Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{job=~\"$cluster-k8s-kubelet\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PVC Total",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 22, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{job=~\"$cluster-k8s-kubelet\", kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Queue Job Count by Queue",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 22, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum(redis_queue_job_count{instance=~\"$host\", namespace=~\"$namespace\", app=~\"$app.*\"}) by (queue, app)",
       "legendFormat": "{{app}}:{{queue}}"
      },
      {
       "expr": "sum(redis_queue_job_count{instance=~\"$host\", namespace=~\"$namespace\", app=~\"$app.*\"}) by (queue, app)",
       "legendFormat": "{{app}}:{{queue}}"
      }
     ]
    },
    {
     "title": "Total Redis Queue Count",
     "type": "stat",
     "gridPos": { "h": 11, "w": 2, "x": 22, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_queue_count{instance=~\"$host\", namespace=~\"$namespace\", app=~\"$app.*\"}",
       "legendFormat": "{{app}}"
      },
      {
       "expr": "redis_queue_count{instance=~\"$host\", namespace=~\"$namespace\", app=~\"$app.*\"}",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NGINX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPM by App:Status:Route",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 22, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum by (route, status, app) (\n  rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}[1m])\n) * 60 > 0",
       "legendFormat": "{{app}}:{{status}}:{{route}}"
      }
     ]
    },
    {
     "title": "RPM by Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"1.*\", app=~\"$app\", namespace=~\"$namespace\"}[1m])) \n/ \nsum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "1XX"
      },
      {
       "expr": "sum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"2.*\", app=~\"$app\", namespace=~\"$namespace\"}[1m])) \n/ \nsum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "2XX"
      },
      {
       "expr": "sum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"3.*\", app=~\"$app\", namespace=~\"$namespace\"}[1m])) \n/ \nsum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "3XX"
      },
      {
       "expr": "sum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"4.*\", app=~\"$app\", namespace=~\"$namespace\"}[1m])) \n/ \nsum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "4XX"
      },
      {
       "expr": "sum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"5.*\", app=~\"$app\", namespace=~\"$namespace\"}[1m])) \n/ \nsum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "5XX"
      }
     ]
    },
    {
     "title": "RPM by App",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((rate(nginx_request_count_total{job=~\"nginx-log-exporter.*\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}[1m])) * 60) by (app)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Request Time by App:Status:Route",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 22, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(nginx_request_time{job=~\"nginx-log-exporter.*\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}) by (route, status, app) > 0",
       "legendFormat": "{{app}}:{{status}}:{{route}}"
      }
     ]
    },
    {
     "title": "Request Time by App",
     "type": "stat",
     "gridPos": { "h": 12, "w": 2, "x": 22, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(nginx_request_time{job=~\"nginx-log-exporter.*\", route!~\"/health\", app=~\"$app\", namespace=~\"$namespace\"}) by (app) > 0",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  }
 ]
}