{
 "title": "TV Left",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_request_count_total{route!~\"/health|/socket.io\", namespace=~\"prod\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", namespace=~\"prod\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBM CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{instance=~\"bare-metal:dbm:.*:.*\", mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPM by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"2.*\", namespace=~\"prod\"}) \n/ \nsum(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", namespace=~\"prod\"})",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"3.*\", namespace=~\"prod\"}) \n/ \nsum(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", namespace=~\"prod\"})",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"4.*\", namespace=~\"prod\"}) \n/ \nsum(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", namespace=~\"prod\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", status=~\"5.*\", namespace=~\"prod\"}) \n/ \nsum(nginx_request_count_total{job=~\"nginx-log-exporter\", route!~\"/health\", namespace=~\"prod\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Kubernetes Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{\n    job=\"k8s-cadvisor-earth\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{\n    job=\"k8s-cadvisor-earth\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Latest Changes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((time() - container_start_time_seconds{job=~\"k8s-cadvisor-earth\", namespace=~\"prod\", pod=~\".+\", image!=\"registry.k8s.io/pause:3.9\", container!~\"POD|cronjob|\"}) \n* on(pod, namespace) group_left(label_app)\nkube_pod_labels{namespace=~\"prod\"}\n) by (namespace, label_app, container) < 3600",
     "legendFormat": "{{label_app}}:{{container}}"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"prod\", phase=~\"Failed\"}) by (phase, pod, namespace) > 0",
     "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"prod\", phase=~\"Pending\"}) by (phase, pod, namespace) > 0",
     "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"prod\", phase=~\"Unknown\"}) by (phase, pod, namespace) > 0",
     "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"prod\", phase=~\"Running|Succeeded\"}) == sum(kube_pod_status_phase{namespace=~\"prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Job Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_queue_job_count{namespace=~\"prod\"})",
     "legendFormat": "{{app}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Redis Job Count by App:Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "sum(redis_queue_job_count{namespace=~\"prod\"}) by (queue, app) > 0",
     "legendFormat": "{{app}}:{{queue}}"
    },
    {
     "expr": "sum(redis_queue_job_count{namespace=~\"prod\"}) by (queue, app) > 0",
     "legendFormat": "{{app}}:{{queue}}"
    }
   ]
  },
  {
   "title": "DBM Rows Read Rate by Schema:Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_info_schema_table_statistics_rows_read_total[30s])) by (schema, table) > 0",
     "legendFormat": "{{schema}}:{{table}}"
    }
   ]
  }
 ]
}