---
- name: Check if user exists
  command: id -u "{{ username }}"
  register: user_check
  failed_when: user_check.rc != 0

- name: Update the user password
  user:
    name: "{{ username }}"
    password: "{{ hashed_password }}"

- name: Verify password update (best-effort)
  debug:
    msg: "Password for user '{{ username }}' has been updated successfully."
