---
- name: Deploy and configure process-exporter
  hosts: all
  become: yes
  tasks:
    - name: Create directory for process-exporter
      file:
        path: /home/hatam/process-exporter
        state: directory
        owner: hatam
        group: hatam
        mode: '0755'

    - name: Create app.py file from template
      template:
        src: app.py.j2
        dest: /home/hatam/process-exporter/app.py
        owner: hatam
        group: hatam
        mode: '0644'

    - name: Create requirements.txt file from template
      template:
        src: requirements.txt.j2
        dest: /home/hatam/process-exporter/requirements.txt
        owner: hatam
        group: hatam
        mode: '0644'

    - name: Create process-exporter service file
      template:
        src: process-exporter.service.j2
        dest: /etc/systemd/system/process-exporter.service
        owner: root
        group: root
        mode: '0644'

    - name: Create Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /home/hatam/process-exporter/venv
      args:
        chdir: /home/hatam/process-exporter
      become_user: hatam

    - name: Install dependencies in the virtual environment
      ansible.builtin.pip:
        requirements: /home/hatam/process-exporter/requirements.txt
        virtualenv: /home/hatam/process-exporter/venv
        virtualenv_command: python3 -m venv
      become_user: hatam


    - name: Reload systemd daemon and enable service
      shell: |
        systemctl daemon-reload
        systemctl enable process-exporter.service --now
