{
 "title": "Node-Exporters",
 "description": "Used Jobs:\n- \"proxmox-node-exporter\"",
 "tags": [
  "node-exporter",
  "proxmox",
  "data",
  "compute",
  "earth"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({job=~\"(.*)-node-exporter\"},instance)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values({job=~\"(.*)-node-exporter\", instance=~\"$cluster.*\"},instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group.*\"},instance)"
    }
   },
   {
    "name": "vm",
    "label": "VM",
    "query": {
     "query": "label_values({job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proxmox",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * avg(1 - rate(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"}[5m]))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((1 - ((node_memory_MemAvailable_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}) / (node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}))) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SWAP Utilization",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(((node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"} - node_memory_SwapFree_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}) / (node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"})) * 100 > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}[$__rate_interval]) * 8)",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}[$__rate_interval]) * 8)",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Load Average 1 minute",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load1{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"})",
       "legendFormat": "Allocated"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"} - node_memory_MemAvailable_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"})",
       "legendFormat": "Used"
      },
      { "expression": "$A - $B", "type": "math" }
     ]
    },
    {
     "title": "CPU Status",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"})",
       "legendFormat": "Allocated"
      },
      { "expression": "$A - $B", "type": "math" }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"} - node_boot_time_seconds{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Utilization by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * avg(1 - rate(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"}[5m])) by (instance)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "System Load Average 1 minute by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Cores by Instance",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"}) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Utilization by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - ((node_memory_MemAvailable_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}) \n     / (node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}))) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Used by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"} - node_memory_MemAvailable_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Memory by Instance",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "SWAP Utilization by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"} - node_memory_SwapFree_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}) / (node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"})) * 100 > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "SWAP Used by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"} - node_memory_SwapFree_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total SWAP by Instance",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}) by (instance) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "172.16.2.X Bytes by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", device=\"vmbr0\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "{{instance}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", device=\"vmbr0\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "{{instance}} - Transmit"
      }
     ]
    },
    {
     "title": "VMs Bytes by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", device=~\"tap.*\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "{{instance}} - Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", device=~\"tap.*\"}[$__rate_interval]) * 8) by (instance)",
       "legendFormat": "{{instance}} - Transmit"
      }
     ]
    },
    {
     "title": "Total Bytes",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}[$__rate_interval]) * 8) ",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\"}[$__rate_interval]) * 8)",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "OS Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"} * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OS Disk Total",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Second Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz-san\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz-san\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz-san\"} * 100",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-01\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-01\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-01\"} * 100",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/san\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/san\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/san\"} * 100",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Second Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz-san\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz-san\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-01\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-01\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/san\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/san\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Second Disk Total",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz-san\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-01\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/san\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Third Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz\"} * 100",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-02\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-02\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-02\"} * 100",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Third Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-02\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-02\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Third Disk Total",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/datastore-9006-datateam-02\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Fourth Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/sanstore-9006-datateam-01\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/sanstore-9006-datateam-01\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/sanstore-9006-datateam-01\"} * 100",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz2\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz2\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz2\"} * 100",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Fourth Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/sanstore-9006-datateam-01\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/sanstore-9006-datateam-01\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz2\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz2\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Fourth Disk Total",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 22, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz/sanstore-9006-datateam-01\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/var/lib/vz2\"}",
       "legendFormat": "{{instance}}:{{mountpoint}}"
      }
     ]
    }
   ]
  },
  { "title": "VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"}[5m]))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - ((node_memory_MemAvailable_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}) / (node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}))) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"} - node_memory_SwapFree_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}) / (node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"})) * 100 > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}[$__rate_interval]) * 8)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}[$__rate_interval]) * 8)",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Load Average 1 minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"} - node_memory_MemAvailable_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"} - node_boot_time_seconds{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "System Load Average 1 minute by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores by Instance",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mode=\"idle\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((node_memory_MemAvailable_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}) \n     / (node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"} - node_memory_MemAvailable_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Memory by Instance",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"} - node_memory_SwapFree_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}) / (node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"})) * 100 > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP Used by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"} - node_memory_SwapFree_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total SWAP by Instance",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "172.16.104.X Bytes by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", device=\"ens18\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", device=\"ens18\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  },
  {
   "title": "Other Interfaces Bytes by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", device!~\"ens18\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", device!~\"ens18\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}[$__rate_interval]) * 8) ",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\"}[$__rate_interval]) * 8)",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "OS Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Disk Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Second Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-2\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-2\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-2\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk2\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk2\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk2\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/home\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/home\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/home\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Second Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-2\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-2\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk2\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk2\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/home\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/home\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Second Disk Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-2\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk2\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/home\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Third Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-3\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-3\"}) / node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-3\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Third Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-3\"} - node_filesystem_avail_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Third Disk Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\", instance!~\"$cluster:proxmox:$host:$vm\", mountpoint=\"/mnt/disk-3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Context Switches by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interrupts by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_intr_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IOps Completed by Instance",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg(irate(node_disk_reads_completed_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} - Reads completed"
    },
    {
     "expr": "avg(irate(node_disk_writes_completed_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk IOps Completed by Device",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg(irate(node_disk_reads_completed_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\"}[$__rate_interval])) by (device)",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "avg(irate(node_disk_writes_completed_total{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\"}[$__rate_interval])) by (device)",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Processes in runnable state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_running{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processes blocked waiting for I/O to complete",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_blocked{job=~\"(.*)-node-exporter\", instance=~\"$cluster:$group:$host:$vm\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Memory Eaters",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "process_mem{job=~\"(.*)-process-exporter\", instance=~\"$vm\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top CPU Eaters",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "process_cpu{job=~\"(.*)-process-exporter\", instance=~\"$vm\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "service_status_enabled{job=~\"(.*)-service-exporter\", instance=~\"$vm\", status=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Other States Services",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "service_status_enabled{job=~\"(.*)-service-exporter\", instance=~\"$vm\", status!=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}